package Exceptions;
import java.io.IOException;
import java.util.Scanner;
import java.io.File;
import java.io.FileNotFoundException;

public class Test {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		/*try{
			Scanner in = new Scanner(new File("text.txt"));
		}
		catch(FileNotFoundException e){
			e.printStackTrace();
		}*/ 
		int a = 4;
		int b = 0;
		try {
			int c = a/b;
			System.out.println(c);
		}
		catch(ArithmeticException e){
			//e.getMessage();
			System.out.println("Error,divide by zerro");
			
		}
		finaly {
			System.out.println("Finaly Block");
		}
		
		
		
		
		
		
		
		
		
		
		
	}

}
